import { useState } from 'react'
import { pricingPlans } from '../data/pricing.js'

function Pricing() {
  const [billing, setBilling] = useState('monthly')

  return (
    <section id="pricing" className="border-b border-slate-200 bg-white px-6 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div className="max-w-xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-indigo-600">Simple, transparent pricing</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">A plan for your next chapter.</h2><p className="mt-4 text-base leading-7 text-slate-600">Start small, grow with confidence, and bring your whole organization into the flow.</p></div><div className="inline-flex self-start rounded-lg border border-slate-200 bg-slate-50 p-1 sm:self-auto" role="group" aria-label="Billing period"><button type="button" onClick={() => setBilling('monthly')} className={`rounded-md px-3 py-2 text-xs font-semibold transition-colors focus-visible:outline-2 focus-visible:outline-indigo-600 ${billing === 'monthly' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-900'}`}>Monthly</button><button type="button" onClick={() => setBilling('yearly')} className={`rounded-md px-3 py-2 text-xs font-semibold transition-colors focus-visible:outline-2 focus-visible:outline-indigo-600 ${billing === 'yearly' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-900'}`}>Yearly <span className="ml-1 text-emerald-600">Save 20%</span></button></div></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{pricingPlans.map((plan) => <article key={plan.name} className={`relative flex flex-col rounded-2xl border p-6 ${plan.popular ? 'border-indigo-500 shadow-[0_16px_40px_-24px_rgba(79,70,229,0.55)]' : 'border-slate-200'}`}>{plan.popular && <span className="absolute -top-3 left-6 rounded-full bg-indigo-600 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">Most popular</span>}<p className="text-sm font-semibold uppercase tracking-[0.14em] text-slate-500">{plan.name}</p><div className="mt-5 flex min-h-12 items-end gap-1"><span className="text-4xl font-semibold tracking-tight text-slate-950">{billing === 'monthly' ? plan.monthlyPrice : plan.yearlyPrice}</span>{plan.suffix && <span className="pb-1 text-xs text-slate-500">{plan.suffix}</span>}</div><p className="mt-4 min-h-12 text-sm leading-6 text-slate-600">{plan.description}</p><a href="#get-started" className={`mt-7 rounded-lg px-4 py-3 text-center text-sm font-semibold transition-colors focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-indigo-600 ${plan.popular ? 'bg-indigo-600 text-white hover:bg-indigo-700' : 'border border-slate-300 text-slate-700 hover:bg-slate-50'}`}>{plan.cta}</a><ul className="mt-8 space-y-4 border-t border-slate-200 pt-6">{plan.features.map((feature) => <li key={feature} className="flex items-center gap-3 text-sm text-slate-600"><span className="text-indigo-600">&#10003;</span>{feature}</li>)}</ul></article>)}</div></div></section>
  )
}

export default Pricing